/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package proj.androway;

public final class R {
    public static final class anim {
        public static final int grow_from_bottom=0x7f040000;
        public static final int grow_from_bottomleft_to_topright=0x7f040001;
        public static final int grow_from_bottomright_to_topleft=0x7f040002;
        public static final int grow_from_top=0x7f040003;
        public static final int grow_from_topleft_to_bottomright=0x7f040004;
        public static final int grow_from_topright_to_bottomleft=0x7f040005;
        public static final int rail=0x7f040006;
        public static final int shrink_from_bottom=0x7f040007;
        public static final int shrink_from_bottomleft_to_topright=0x7f040008;
        public static final int shrink_from_bottomright_to_topleft=0x7f040009;
        public static final int shrink_from_top=0x7f04000a;
        public static final int shrink_from_topleft_to_bottomright=0x7f04000b;
        public static final int shrink_from_topright_to_bottomleft=0x7f04000c;
        public static final int slide_left_in=0x7f04000d;
        public static final int slide_left_out=0x7f04000e;
        public static final int slide_right_in=0x7f04000f;
        public static final int slide_right_out=0x7f040010;
    }
    public static final class array {
        public static final int language_names=0x7f060002;
        public static final int language_values=0x7f060003;
        public static final int orientation_names=0x7f060000;
        public static final int orientation_values=0x7f060001;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int action_item_selected=0x7f020000;
        public static final int arrow_move=0x7f020001;
        public static final int balance_bg=0x7f020002;
        public static final int balance_scale=0x7f020003;
        public static final int battery_icon=0x7f020004;
        public static final int battery_icon_10=0x7f020005;
        public static final int battery_icon_100=0x7f020006;
        public static final int battery_icon_25=0x7f020007;
        public static final int battery_icon_5=0x7f020008;
        public static final int battery_icon_50=0x7f020009;
        public static final int battery_icon_75=0x7f02000a;
        public static final int bluetooth_icon=0x7f02000b;
        public static final int bt_connect_icon=0x7f02000c;
        public static final int bt_disconnect_icon=0x7f02000d;
        public static final int btn_strip_trans_left=0x7f02000e;
        public static final int btn_strip_trans_left_normal=0x7f02000f;
        public static final int btn_strip_trans_left_pressed=0x7f020010;
        public static final int btn_strip_trans_left_selected=0x7f020011;
        public static final int btn_strip_trans_middle=0x7f020012;
        public static final int btn_strip_trans_middle_normal=0x7f020013;
        public static final int btn_strip_trans_middle_pressed=0x7f020014;
        public static final int btn_strip_trans_middle_selected=0x7f020015;
        public static final int btn_strip_trans_right=0x7f020016;
        public static final int btn_strip_trans_right_normal=0x7f020017;
        public static final int btn_strip_trans_right_pressed=0x7f020018;
        public static final int btn_strip_trans_right_selected=0x7f020019;
        public static final int compass=0x7f02001a;
        public static final int dialog_devider_h=0x7f02001b;
        public static final int dialog_devider_v=0x7f02001c;
        public static final int dir_arrow_left=0x7f02001d;
        public static final int dir_arrow_right=0x7f02001e;
        public static final int dir_arrow_straight=0x7f02001f;
        public static final int direction_bg=0x7f020020;
        public static final int exit_icon=0x7f020021;
        public static final int exit_icon_normal=0x7f020022;
        public static final int exit_icon_selected=0x7f020023;
        public static final int first_locked=0x7f020024;
        public static final int first_second_locked=0x7f020025;
        public static final int ic_dialog_bluetooth=0x7f020026;
        public static final int ic_dialog_login=0x7f020027;
        public static final int ic_menu_exit=0x7f020028;
        public static final int ic_menu_info=0x7f020029;
        public static final int ic_menu_settings=0x7f02002a;
        public static final int ic_menu_stop=0x7f02002b;
        public static final int inclination_bg=0x7f02002c;
        public static final int launcher_icon=0x7f02002d;
        public static final int lego_wheel=0x7f02002e;
        public static final int log_local_icon=0x7f02002f;
        public static final int log_web_icon=0x7f020030;
        public static final int notification_icon=0x7f020031;
        public static final int progress_bar=0x7f020032;
        public static final int quickcontact_arrow_down=0x7f020033;
        public static final int quickcontact_arrow_up=0x7f020034;
        public static final int quickcontact_bottom_frame=0x7f020035;
        public static final int quickcontact_disambig_bottom_bg=0x7f020036;
        public static final int quickcontact_disambig_divider=0x7f020037;
        public static final int quickcontact_drop_shadow=0x7f020038;
        public static final int quickcontact_photo_frame=0x7f020039;
        public static final int quickcontact_slider_background=0x7f02003a;
        public static final int quickcontact_slider_btn=0x7f02003b;
        public static final int quickcontact_slider_btn_normal=0x7f02003c;
        public static final int quickcontact_slider_btn_on=0x7f02003d;
        public static final int quickcontact_slider_btn_pressed=0x7f02003e;
        public static final int quickcontact_slider_btn_selected=0x7f02003f;
        public static final int quickcontact_slider_grip_left=0x7f020040;
        public static final int quickcontact_slider_grip_right=0x7f020041;
        public static final int quickcontact_top_frame=0x7f020042;
        public static final int second_locked=0x7f020043;
        public static final int segway_body_direction=0x7f020044;
        public static final int segway_body_inclination=0x7f020045;
        public static final int settings_icon=0x7f020046;
        public static final int settings_icon_normal=0x7f020047;
        public static final int settings_icon_selected=0x7f020048;
        public static final int start_session_icon=0x7f020049;
        public static final int start_session_icon_normal=0x7f02004a;
        public static final int start_session_icon_selected=0x7f02004b;
        public static final int title_bar_bg=0x7f02004c;
        public static final int title_text=0x7f02004d;
        public static final int transparent=0x7f02004e;
        public static final int view_old_session_icon=0x7f02004f;
        public static final int view_old_session_icon_normal=0x7f020050;
        public static final int view_old_session_icon_selected=0x7f020051;
    }
    public static final class id {
        public static final int arrow_down=0x7f0a000c;
        public static final int arrow_up=0x7f0a0008;
        public static final int balance=0x7f0a0002;
        public static final int balance_holder=0x7f0a0003;
        public static final int battery_button=0x7f0a0012;
        public static final int block1=0x7f0a000d;
        public static final int block1_flipper=0x7f0a000e;
        public static final int block2=0x7f0a000f;
        public static final int block2_flipper=0x7f0a0010;
        public static final int blocked_block=0x7f0a0016;
        public static final int bluetooth_button=0x7f0a0013;
        public static final int compass=0x7f0a0004;
        public static final int footer=0x7f0a000b;
        public static final int header2=0x7f0a0007;
        public static final int icon=0x7f0a0000;
        public static final int log_web_button=0x7f0a0011;
        public static final int main_progress_bar=0x7f0a0015;
        public static final int menu_quit_session=0x7f0a0020;
        public static final int menu_settings=0x7f0a001f;
        public static final int scroll=0x7f0a0009;
        public static final int segway_body=0x7f0a0005;
        public static final int start_session=0x7f0a0017;
        public static final int start_session_icon=0x7f0a0018;
        public static final int start_session_text=0x7f0a0019;
        public static final int title=0x7f0a0001;
        public static final int titlebar=0x7f0a0014;
        public static final int tracks=0x7f0a000a;
        public static final int view_old_session=0x7f0a001a;
        public static final int view_old_session_icon=0x7f0a001b;
        public static final int view_settings=0x7f0a001c;
        public static final int view_settings_icon=0x7f0a001d;
        public static final int webview=0x7f0a001e;
        public static final int window_tint=0x7f0a0006;
    }
    public static final class layout {
        public static final int action_item=0x7f030000;
        public static final int balance=0x7f030001;
        public static final int compass=0x7f030002;
        public static final int direction=0x7f030003;
        public static final int inclination=0x7f030004;
        public static final int main=0x7f030005;
        public static final int quickaction=0x7f030006;
        public static final int running_session=0x7f030007;
        public static final int statusbar=0x7f030008;
        public static final int titlebar=0x7f030009;
        public static final int view_dialog=0x7f03000a;
        public static final int view_old_session=0x7f03000b;
    }
    public static final class menu {
        public static final int running_session_menu=0x7f090000;
    }
    public static final class string {
        public static final int ConstructingLoggingManagerFailedException=0x7f07003d;
        public static final int HttpGetRequestFailedException=0x7f07003c;
        public static final int HttpPostRequestFailedException=0x7f07003b;
        public static final int MapIsEmptyException=0x7f07003a;
        /**  Exception messages 
 Exception messages 
 Exception messages 
         */
        public static final int MaxPoolSizeReachedException=0x7f070038;
        public static final int NotSupportedQueryTypeException=0x7f070039;
        /**  UI Settings View 
 UI Settings View 
 UI Settings View 
         */
        public static final int accountSettings=0x7f07001c;
        /**  Logging 
 Logging 
 Logging 
         */
        public static final int add=0x7f070031;
        public static final int added=0x7f070035;
        public static final int app_label=0x7f070001;
        public static final int app_name=0x7f070000;
        public static final int block1LockedSummary=0x7f07002a;
        public static final int block1LockedTitle=0x7f070029;
        public static final int block2LockedSummary=0x7f07002c;
        public static final int block2LockedTitle=0x7f07002b;
        public static final int bluetoothInvalid=0x7f070026;
        public static final int bluetoothSummary=0x7f070025;
        public static final int bluetoothTitle=0x7f070024;
        public static final int bluetooth_message=0x7f070011;
        public static final int bluetooth_title=0x7f070010;
        /**  UI 
 UI 
 UI 
         */
        public static final int choose_action=0x7f070002;
        public static final int connect=0x7f070006;
        public static final int disconnect=0x7f070007;
        public static final int emailInvalid=0x7f070020;
        public static final int emailSummary=0x7f07001f;
        public static final int emailTitle=0x7f07001e;
        public static final int empty=0x7f070037;
        public static final int error_message=0x7f070013;
        public static final int error_title=0x7f070012;
        public static final int exit_app=0x7f07000a;
        public static final int format=0x7f070034;
        public static final int get=0x7f070032;
        public static final int invalid=0x7f07000c;
        public static final int languageSummary=0x7f070030;
        public static final int languageTitle=0x7f07002f;
        public static final int left_during_login=0x7f070015;
        public static final int logOnlineSummary=0x7f070028;
        public static final int logOnlineTitle=0x7f070027;
        public static final int login_failed_message=0x7f070014;
        public static final int login_message=0x7f07000f;
        /**  Dialog string values (on session start) 
 Dialog string values (on session start) 
 Dialog string values (on session start) 
         */
        public static final int login_title=0x7f07000e;
        public static final int ok=0x7f07000b;
        public static final int orientationSummary=0x7f07002e;
        public static final int orientationTitle=0x7f07002d;
        public static final int passwordInvalid=0x7f070023;
        public static final int passwordSummary=0x7f070022;
        public static final int passwordTitle=0x7f070021;
        public static final int remove=0x7f070033;
        public static final int removed=0x7f070036;
        public static final int session_hold_message=0x7f07001b;
        public static final int session_hold_ticker=0x7f070019;
        public static final int session_hold_title=0x7f07001a;
        public static final int settings=0x7f070008;
        public static final int show_running_session=0x7f070004;
        public static final int start_new_session=0x7f070003;
        public static final int start_session_message=0x7f070018;
        /**  Notification string values 
 Notification string values 
 Notification string values 
         */
        public static final int start_session_ticker=0x7f070016;
        public static final int start_session_title=0x7f070017;
        public static final int stop_session=0x7f07000d;
        public static final int systemSettings=0x7f07001d;
        public static final int view_old_session=0x7f070005;
        public static final int view_settings=0x7f070009;
    }
    public static final class style {
        public static final int Animations=0x7f080007;
        /**  PopDownMenu 
         */
        public static final int Animations_PopDownMenu=0x7f080008;
        public static final int Animations_PopDownMenu_Center=0x7f08000b;
        public static final int Animations_PopDownMenu_Left=0x7f080009;
        public static final int Animations_PopDownMenu_Right=0x7f08000a;
        /**  PopUpMenu 
         */
        public static final int Animations_PopUpMenu=0x7f08000c;
        public static final int Animations_PopUpMenu_Center=0x7f08000f;
        public static final int Animations_PopUpMenu_Left=0x7f08000d;
        public static final int Animations_PopUpMenu_Right=0x7f08000e;
        public static final int BlockComponent=0x7f080003;
        public static final int GestureOverlay=0x7f080002;
        public static final int StatusBarLeft=0x7f080004;
        public static final int StatusBarMiddle=0x7f080005;
        public static final int StatusBarRight=0x7f080006;
        public static final int TitleBar=0x7f080001;
        public static final int WindowTint=0x7f080000;
    }
    public static final class xml {
        public static final int settings=0x7f050000;
    }
}
