/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package proj.androway;

public final class Manifest {
    public static final class permission {
        /**  Create a custom permission to shield off access to the Session Service 
         */
        public static final String ACCESS_SESSION="proj.androway.main.ACCESS_SESSION";
    }
}
