/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package androway.ui;

public final class R {
    public static final class anim {
        public static final int grow_from_bottom=0x7f040000;
        public static final int grow_from_bottomleft_to_topright=0x7f040001;
        public static final int grow_from_bottomright_to_topleft=0x7f040002;
        public static final int grow_from_top=0x7f040003;
        public static final int grow_from_topleft_to_bottomright=0x7f040004;
        public static final int grow_from_topright_to_bottomleft=0x7f040005;
        public static final int rail=0x7f040006;
        public static final int shrink_from_bottom=0x7f040007;
        public static final int shrink_from_bottomleft_to_topright=0x7f040008;
        public static final int shrink_from_bottomright_to_topleft=0x7f040009;
        public static final int shrink_from_top=0x7f04000a;
        public static final int shrink_from_topleft_to_bottomright=0x7f04000b;
        public static final int shrink_from_topright_to_bottomleft=0x7f04000c;
        public static final int slide_left_in=0x7f04000d;
        public static final int slide_left_out=0x7f04000e;
        public static final int slide_right_in=0x7f04000f;
        public static final int slide_right_out=0x7f040010;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int action_item_selected=0x7f020000;
        public static final int arrow_move=0x7f020001;
        public static final int balance_bg=0x7f020002;
        public static final int balance_scale=0x7f020003;
        public static final int battery_icon=0x7f020004;
        public static final int bluetooth_icon=0x7f020005;
        public static final int bt_connect_icon=0x7f020006;
        public static final int bt_disconnect_icon=0x7f020007;
        public static final int btn_strip_trans_left=0x7f020008;
        public static final int btn_strip_trans_left_normal=0x7f020009;
        public static final int btn_strip_trans_left_pressed=0x7f02000a;
        public static final int btn_strip_trans_left_selected=0x7f02000b;
        public static final int btn_strip_trans_middle=0x7f02000c;
        public static final int btn_strip_trans_middle_normal=0x7f02000d;
        public static final int btn_strip_trans_middle_pressed=0x7f02000e;
        public static final int btn_strip_trans_middle_selected=0x7f02000f;
        public static final int btn_strip_trans_right=0x7f020010;
        public static final int btn_strip_trans_right_normal=0x7f020011;
        public static final int btn_strip_trans_right_pressed=0x7f020012;
        public static final int btn_strip_trans_right_selected=0x7f020013;
        public static final int compass=0x7f020014;
        public static final int dir_arrow_left=0x7f020015;
        public static final int dir_arrow_right=0x7f020016;
        public static final int dir_arrow_straight=0x7f020017;
        public static final int direction_bg=0x7f020018;
        public static final int inclination_bg=0x7f020019;
        public static final int launcher_icon=0x7f02001a;
        public static final int lego_wheel=0x7f02001b;
        public static final int log_web_icon=0x7f02001c;
        public static final int quickcontact_arrow_down=0x7f02001d;
        public static final int quickcontact_arrow_up=0x7f02001e;
        public static final int quickcontact_bottom_frame=0x7f02001f;
        public static final int quickcontact_disambig_bottom_bg=0x7f020020;
        public static final int quickcontact_disambig_divider=0x7f020021;
        public static final int quickcontact_drop_shadow=0x7f020022;
        public static final int quickcontact_photo_frame=0x7f020023;
        public static final int quickcontact_slider_background=0x7f020024;
        public static final int quickcontact_slider_btn=0x7f020025;
        public static final int quickcontact_slider_btn_normal=0x7f020026;
        public static final int quickcontact_slider_btn_on=0x7f020027;
        public static final int quickcontact_slider_btn_pressed=0x7f020028;
        public static final int quickcontact_slider_btn_selected=0x7f020029;
        public static final int quickcontact_slider_grip_left=0x7f02002a;
        public static final int quickcontact_slider_grip_right=0x7f02002b;
        public static final int quickcontact_top_frame=0x7f02002c;
        public static final int segway_body_direction=0x7f02002d;
        public static final int segway_body_inclination=0x7f02002e;
        public static final int settings_icon=0x7f02002f;
        public static final int title_bar_bg=0x7f020030;
        public static final int title_text=0x7f020031;
    }
    public static final class id {
        public static final int arrow_down=0x7f070010;
        public static final int arrow_up=0x7f07000c;
        public static final int balance=0x7f070002;
        public static final int balance_holder=0x7f070003;
        public static final int battery_button=0x7f070012;
        public static final int block1=0x7f070007;
        public static final int block1_flipper=0x7f070008;
        public static final int block2=0x7f070009;
        public static final int block2_flipper=0x7f07000a;
        public static final int bluetooth_button=0x7f070013;
        public static final int compass=0x7f070004;
        public static final int footer=0x7f07000f;
        public static final int header2=0x7f07000b;
        public static final int icon=0x7f070000;
        public static final int log_web_button=0x7f070011;
        public static final int scroll=0x7f07000d;
        public static final int segway_body=0x7f070005;
        public static final int title=0x7f070001;
        public static final int tracks=0x7f07000e;
        public static final int window_tint=0x7f070006;
    }
    public static final class layout {
        public static final int action_item=0x7f030000;
        public static final int balance=0x7f030001;
        public static final int compass=0x7f030002;
        public static final int direction=0x7f030003;
        public static final int inclination=0x7f030004;
        public static final int main=0x7f030005;
        public static final int quickaction=0x7f030006;
        public static final int statusbar=0x7f030007;
        public static final int temperature=0x7f030008;
        public static final int titlebar=0x7f030009;
    }
    public static final class string {
        public static final int HttpGetRequestFailedException=0x7f050010;
        public static final int HttpPostRequestFailedException=0x7f05000f;
        public static final int MapIsEmptyException=0x7f05000e;
        /**  Exception messages 
         */
        public static final int MaxPoolSizeReachedException=0x7f05000c;
        public static final int NotSupportedQueryTypeException=0x7f05000d;
        /**  Logging 
         */
        public static final int add=0x7f050005;
        public static final int added=0x7f050009;
        public static final int app_label=0x7f050001;
        public static final int app_name=0x7f050000;
        /**  UI 
         */
        public static final int connect=0x7f050002;
        public static final int disconnect=0x7f050003;
        public static final int empty=0x7f05000b;
        public static final int format=0x7f050008;
        public static final int get=0x7f050006;
        public static final int remove=0x7f050007;
        public static final int removed=0x7f05000a;
        public static final int settings=0x7f050004;
    }
    public static final class style {
        public static final int Animations=0x7f060007;
        /**  PopDownMenu 
         */
        public static final int Animations_PopDownMenu=0x7f060008;
        public static final int Animations_PopDownMenu_Center=0x7f06000b;
        public static final int Animations_PopDownMenu_Left=0x7f060009;
        public static final int Animations_PopDownMenu_Right=0x7f06000a;
        /**  PopUpMenu 
         */
        public static final int Animations_PopUpMenu=0x7f06000c;
        public static final int Animations_PopUpMenu_Center=0x7f06000f;
        public static final int Animations_PopUpMenu_Left=0x7f06000d;
        public static final int Animations_PopUpMenu_Right=0x7f06000e;
        public static final int BlockComponent=0x7f060003;
        public static final int GestureOverlay=0x7f060002;
        public static final int StatusBarLeft=0x7f060004;
        public static final int StatusBarMiddle=0x7f060005;
        public static final int StatusBarRight=0x7f060006;
        public static final int TitleBar=0x7f060001;
        public static final int WindowTint=0x7f060000;
    }
}
